### ISSUE TITLE
Proxy Support

### ISSUE THREAD

**Issue by tcanavan** [pact-foundation/pact-broker-docker#9]
# Pre issue-raising checklist

I have already (please mark the applicable with an `x`):

* [ x] Confirmed this is the right place to raise the issue - only issues related to the Dockerization of the Pact Broker should be raised here. Issues related to the Pact Broker application itself should be raised in the [Pact Broker](https://github.com/pact-foundation/pact_broker) project.
* [ x] Upgraded to the latest Pact Broker Docker image OR
* [ x] Checked the [CHANGELOG](/CHANGELOG.md) to see if the issue I am about to raise has been fixed
* [ x] Read the [Troubleshooting](https://github.com/pact-foundation/pact-broker-docker/wiki/Troubleshooting) page

## Software versions

* **pact-broker gem version:** eg 2.3.1
* **pact-broker docker version:** eg 2.3.1-1
* **OS**: e.g. Mac OSX 10.11.5
* **pact broker client details:** eg. pact-ruby-standalone CLI v 1.23.0

## Expected behaviour

Webhook is triggered and my jenkins job is executed.

## Actual behaviour

500 Error because I am going through a proxy. HTTPS_PROXY and NO_PROXY variables are set for broker

## Steps to reproduce

Trigger webhook in pact  broker ui. Call jenkins server from behind proxy.

**Comment by bethesque** [comment]
Try using the lowercase equivalents (eg https_proxy).

**Comment by tcanavan** [comment]
tried that but still getting 500 internal server error

```
{
  "error": {
    "message": "end of file reached",
    "backtrace": [
      "/usr/local/lib/ruby/2.6.0/net/protocol.rb:225:in `rbuf_fill'",
      "/usr/local/lib/ruby/2.6.0/net/protocol.rb:191:in `readuntil'",
      "/usr/local/lib/ruby/2.6.0/net/protocol.rb:201:in `readline'",
      "/usr/local/lib/ruby/2.6.0/net/http/response.rb:40:in `read_status_line'",
      "/usr/local/lib/ruby/2.6.0/net/http/response.rb:29:in `read_new'",
      "/usr/local/lib/ruby/2.6.0/net/http.rb:969:in `connect'",
      "/usr/local/lib/ruby/2.6.0/net/http.rb:930:in `do_start'",
      "/usr/local/lib/ruby/2.6.0/net/http.rb:919:in `start'",
      "/usr/local/lib/ruby/2.6.0/net/http.rb:605:in `start'",
      "/pact_broker/vendor/bundle/ruby/2.6.0/gems/pact_broker-2.31.0/lib/pact_broker/domain/webhook_request.rb:134:in `do_request'",
      "/pact_broker/vendor/bundle/ruby/2.6.0/gems/pact_broker-2.31.0/lib/pact_broker/domain/webhook_request.rb:108:in `execute_and_build_result'",
      "/pact_broker/vendor/bundle/ruby/2.6.0/gems/pact_broker-2.31.0/lib/pact_broker/domain/webhook_request.rb:96:in `execute'",
      "/pact_broker/vendor/bundle/ruby/2.6.0/gems/pact_broker-2.31.0/lib/pact_broker/domain/webhook.rb:45:in `execute'",
      "/pact_broker/vendor/bundle/ruby/2.6.0/gems/pact_broker-2.31.0/lib/pact_broker/webhooks/service.rb:74:in `test_execution'",
      "/pact_broker/vendor/bundle/ruby/2.6.0/gems/pact_broker-2.31.0/lib/pact_broker/api/resources/webhook_execution.rb:17:in `process_post'",
      "/pact_broker/vendor/bundle/ruby/2.6.0/gems/webmachine-1.5.0/lib/webmachine/decision/flow.rb:428:in `n11'",
      "/pact_broker/vendor/bundle/ruby/2.6.0/gems/webmachine-1.5.0/lib/webmachine/decision/fsm.rb:31:in `block (2 levels) in run'",
      "/pact_broker/vendor/bundle/ruby/2.6.0/gems/webmachine-1.5.0/lib/webmachine/decision/fsm.rb:51:in `handle_exceptions'",
      "/pact_broker/vendor/bundle/ruby/2.6.0/gems/webmachine-1.5.0/lib/webmachine/decision/fsm.rb:31:in `block in run'",
      "/pact_broker/vendor/bundle/ruby/2.6.0/gems/webmachine-1.5.0/lib/webmachine/decision/fsm.rb:29:in `loop'",
      "/pact_broker/vendor/bundle/ruby/2.6.0/gems/webmachine-1.5.0/lib/webmachine/decision/fsm.rb:29:in `run'",
      "/pact_broker/vendor/bundle/ruby/2.6.0/gems/webmachine-1.5.0/lib/webmachine/dispatcher.rb:46:in `block in dispatch'",
      "/pact_broker/vendor/bundle/ruby/2.6.0/gems/as-notifications-1.0.1/lib/as/notifications.rb:161:in `instrument'",
      "/pact_broker/vendor/bundle/ruby/2.6.0/gems/webmachine-1.5.0/lib/webmachine/events.rb:75:in `instrument'",
      "/pact_broker/vendor/bundle/ruby/2.6.0/gems/webmachine-1.5.0/lib/webmachine/dispatcher.rb:45:in `dispatch'",
      "/pact_broker/vendor/bundle/ruby/2.6.0/gems/webmachine-1.5.0/lib/webmachine/adapters/rack.rb:68:in `call'",
      "/pact_broker/vendor/bundle/ruby/2.6.0/gems/pact_broker-2.31.0/lib/rack/pact_broker/database_transaction.rb:44:in `block in call_with_transaction'",
      "/pact_broker/vendor/bundle/ruby/2.6.0/gems/sequel-5.19.0/lib/sequel/database/transactions.rb:245:in `_transaction'",
      "/pact_broker/vendor/bundle/ruby/2.6.0/gems/sequel-5.19.0/lib/sequel/database/transactions.rb:220:in `block in transaction'",
      "/pact_broker/vendor/bundle/ruby/2.6.0/gems/sequel-5.19.0/lib/sequel/connection_pool/threaded.rb:92:in `hold'",
      "/pact_broker/vendor/bundle/ruby/2.6.0/gems/sequel-5.19.0/lib/sequel/database/connecting.rb:270:in `synchronize'",
      "/pact_broker/vendor/bundle/ruby/2.6.0/gems/sequel-5.19.0/lib/sequel/database/transactions.rb:186:in `transaction'",
      "/pact_broker/vendor/bundle/ruby/2.6.0/gems/pact_broker-2.31.0/lib/rack/pact_broker/database_transaction.rb:43:in `call_with_transaction'",
      "/pact_broker/vendor/bundle/ruby/2.6.0/gems/pact_broker-2.31.0/lib/rack/pact_broker/database_transaction.rb:25:in `call'",
      "/pact_broker/vendor/bundle/ruby/2.6.0/gems/pact_broker-2.31.0/lib/rack/pact_broker/convert_404_to_hal.rb:10:in `call'",
      "/pact_broker/vendor/bundle/ruby/2.6.0/gems/pact_broker-2.31.0/lib/rack/pact_broker/no_auth.rb:9:in `call'",
      "/pact_broker/vendor/bundle/ruby/2.6.0/gems/rack-2.0.7/lib/rack/builder.rb:153:in `call'",
      "/pact_broker/vendor/bundle/ruby/2.6.0/gems/rack-2.0.7/lib/rack/cascade.rb:33:in `block in call'",
      "/pact_broker/vendor/bundle/ruby/2.6.0/gems/rack-2.0.7/lib/rack/cascade.rb:24:in `each'",
      "/pact_broker/vendor/bundle/ruby/2.6.0/gems/rack-2.0.7/lib/rack/cascade.rb:24:in `call'",
      "/pact_broker/vendor/bundle/ruby/2.6.0/gems/rack-2.0.7/lib/rack/urlmap.rb:68:in `block in call'",
      "/pact_broker/vendor/bundle/ruby/2.6.0/gems/rack-2.0.7/lib/rack/urlmap.rb:53:in `each'",
      "/pact_broker/vendor/bundle/ruby/2.6.0/gems/rack-2.0.7/lib/rack/urlmap.rb:53:in `call'",
      "/pact_broker/vendor/bundle/ruby/2.6.0/gems/rack-2.0.7/lib/rack/static.rb:149:in `call'",
      "/pact_broker/vendor/bundle/ruby/2.6.0/gems/pact_broker-2.31.0/lib/rack/hal_browser/redirect.rb:20:in `call'",
      "/pact_broker/vendor/bundle/ruby/2.6.0/gems/pact_broker-2.31.0/lib/rack/pact_broker/convert_file_extension_to_accept_header.rb:26:in `call'",
      "/pact_broker/vendor/bundle/ruby/2.6.0/gems/rack-2.0.7/lib/rack/static.rb:149:in `call'",
      "/pact_broker/vendor/bundle/ruby/2.6.0/gems/rack-2.0.7/lib/rack/static.rb:149:in `call'",
      "/pact_broker/vendor/bundle/ruby/2.6.0/gems/pact_broker-2.31.0/lib/rack/pact_broker/add_pact_broker_version_header.rb:14:in `call'",
      "/pact_broker/vendor/bundle/ruby/2.6.0/gems/pact_broker-2.31.0/lib/rack/pact_broker/store_base_url.rb:10:in `call'",
      "/pact_broker/vendor/bundle/ruby/2.6.0/gems/pact_broker-2.31.0/lib/rack/pact_broker/reset_thread_data.rb:13:in `call'",
      "/pact_broker/vendor/bundle/ruby/2.6.0/gems/pact_broker-2.31.0/lib/rack/pact_broker/invalid_uri_protection.rb:16:in `call'",
      "/pact_broker/vendor/bundle/ruby/2.6.0/gems/rack-protection-2.0.5/lib/rack/protection/xss_header.rb:18:in `call'",
      "/pact_broker/vendor/bundle/ruby/2.6.0/gems/rack-protection-2.0.5/lib/rack/protection/json_csrf.rb:26:in `call'",
      "/pact_broker/vendor/bundle/ruby/2.6.0/gems/rack-protection-2.0.5/lib/rack/protection/base.rb:50:in `call'",
      "/pact_broker/vendor/bundle/ruby/2.6.0/gems/rack-protection-2.0.5/lib/rack/protection/frame_options.rb:31:in `call'",
      "/pact_broker/vendor/bundle/ruby/2.6.0/gems/rack-2.0.7/lib/rack/builder.rb:153:in `call'",
      "/pact_broker/vendor/bundle/ruby/2.6.0/gems/pact_broker-2.31.0/lib/pact_broker/app.rb:64:in `call'",
      "/pact_broker/vendor/bundle/ruby/2.6.0/gems/rack-2.0.7/lib/rack/auth/basic.rb:25:in `call'",
      "/pact_broker/basic_auth.rb:33:in `call'",
      "/pact_broker/vendor/bundle/ruby/2.6.0/gems/puma-3.12.1/lib/puma/configuration.rb:227:in `call'",
      "/pact_broker/vendor/bundle/ruby/2.6.0/gems/puma-3.12.1/lib/puma/server.rb:660:in `handle_request'",
      "/pact_broker/vendor/bundle/ruby/2.6.0/gems/puma-3.12.1/lib/puma/server.rb:474:in `process_client'",
      "/pact_broker/vendor/bundle/ruby/2.6.0/gems/puma-3.12.1/lib/puma/server.rb:334:in `block in run'",
      "/pact_broker/vendor/bundle/ruby/2.6.0/gems/puma-3.12.1/lib/puma/thread_pool.rb:135:in `block in spawn_thread'"
    ]
```

**Comment by bethesque** [comment]
Is that the same error as you were getting before, or a different one?

**Comment by bethesque** [comment]
By the way, you didn't fill in the version information in the bug reporting section. What version are you using?

**Comment by tcanavan** [comment]
Version pactfoundation/pact-broker:edge installed in Cloud Foundry

> Is that the same error as you were getting before, or a different one?
Same error

**Comment by bethesque** [comment]
Can you get into a session on the docker container? If you can, let's do some debugging.

Try running `irb` on the container and then execute:

```
require 'net/http'
require 'uri'

uri = URI("https://postman-echo.com/post")
req = Net::HTTP::Post.new(uri)
response =  Net::HTTP.start(uri.hostname, uri.port, :ENV, use_ssl: true) do |http|
  http.request req
end
puts response.code
puts response.to_hash
puts response.body
```

See if you get a response.

**Comment by bethesque** [comment]
Closing due to inactivity.
